import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import os
import logging
from datetime import datetime
from dotenv import load_dotenv
from fetcher import fetch_all_feeds, filter_by_keywords
from deduplicator import filter_new_items
from summariser import summarise_all

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# User defined keywords - edit these to your interests
USER_KEYWORDS = [
    # Security
    "vulnerability", "exploit", "ransomware", "zero-day", "CVE",
    "malware", "phishing", "breach", "firewall", "intrusion",
    # AI
    "AI", "LLM", "machine learning", "neural network", "Claude",
    "GPT", "artificial intelligence", "agentic",
    # Bastion/BSV
    "BSV", "Bitcoin SV", "Bastion", "blockchain", "post-quantum",
    "zero knowledge", "cryptography", "privacy protocol",
    # Tech
    "cybersecurity", "SIEM", "SOC", "threat intelligence",
    "network security", "cloud security"
]

# Obsidian vault output path - update this to your vault location
OBSIDIAN_PATH = os.path.expanduser("~/Documents/MyVault/Inbox")

def generate_report(summaries: dict, period: str) -> str:
    """Build structured Markdown report"""
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    report = f"""# 🛡️ Intel Report — {date_str} {period}
*Generated: {time_str} | LeightonSec Intelligence Pipeline*

---

"""
    category_icons = {
        "security": "🔒 Security News",
        "ai_research": "🤖 AI Research",
        "bsv_bastion": "⛓️ BSV & Bastion",
        "cve": "🚨 CVE & Vulnerabilities",
        "custom": "🎯 Custom Topics"
    }

    for category, summary in summaries.items():
        title = category_icons.get(category, f"📌 {category.title()}")
        report += f"## {title}\n\n"
        report += f"{summary}\n\n"
        report += "---\n\n"

    report += "*Report generated by intel-pipeline — LeightonSec*\n"
    return report

def save_report(report: str, period: str):
    """Save report to Obsidian inbox and local reports folder"""
    now = datetime.now()
    filename = f"Intel-{now.strftime('%Y-%m-%d')}-{period}.md"

    # Save to local reports folder
    os.makedirs("reports", exist_ok=True)
    local_path = os.path.join("reports", filename)
    with open(local_path, "w") as f:
        f.write(report)
    logger.info(f"Report saved locally: {local_path}")

    # Save to Obsidian inbox if path exists
    if os.path.exists(OBSIDIAN_PATH):
        obsidian_file = os.path.join(OBSIDIAN_PATH, filename)
        with open(obsidian_file, "w") as f:
            f.write(report)
        logger.info(f"Report saved to Obsidian: {obsidian_file}")
    else:
        logger.warning(f"Obsidian path not found: {OBSIDIAN_PATH}")

def run_pipeline(period: str = "AM"):
    """Main pipeline execution"""
    logger.info(f"Starting intel pipeline — {period} run")

    # Fetch all feeds
    logger.info("Fetching feeds...")
    raw_items = fetch_all_feeds()

    # Filter by keywords
    logger.info("Filtering by keywords...")
    filtered_items = {}
    for category, items in raw_items.items():
        filtered = filter_by_keywords(items, USER_KEYWORDS)
        filtered = filter_new_items(filtered)
        filtered_items[category] = filtered
        logger.info(f"{category}: {len(items)} fetched → {len(filtered)} new & relevant")

    # Summarise
    logger.info("Summarising with Claude API...")
    summaries = summarise_all(filtered_items)

    # Generate and save report
    report = generate_report(summaries, period)
    save_report(report, period)

    logger.info("Pipeline complete.")
    return report

if __name__ == "__main__":
    run_pipeline("AM")